management:
  endpoints:
    web:
      exposure:
        include: "*"
path:
    bar: http://bar:61011/

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG