management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
        - id: foo
          uri: http://foo:61010/
          predicates:
          - Path=/foo/**
          filters:
          - StripPrefix=1
        - id: bar
          uri: http://bar:61011/
          predicates:
          - Path=/bar/**
          filters:
          - StripPrefix=1