spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: classpath:/config
management:
    endpoints:
        web:
            exposure:
                include: "*"